// Codex PNGs (design/codex/photos) → bundled progressive JPEGs (mobile/assets/images),
// then regenerate mobile/src/assets/images.ts (Metro needs literal require()s).
// Every key the app uses is listed in SLOTS; a slot whose photo does not exist
// yet points at the ONE placeholder, so swapping in the real image later is
// just re-running this script.
//
//   node design/tools/process-images.mjs
import sharp from 'sharp';
import { existsSync, mkdirSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SRC = join(ROOT, 'design', 'codex', 'photos');
const OUT = join(ROOT, 'mobile', 'assets', 'images');
mkdirSync(OUT, { recursive: true });

const SIZE = { portrait: [1080, 1440], square: [720, 720], wide: [1600, 900], land: [1200, 900] };
// key → [source name, size, gravity]
const SLOTS = {
  'discover-budget': ['discover-budget', 'portrait', 'north'],
  'discover-compare': ['discover-compare', 'portrait', 'north'],
  'discover-finish': ['discover-finish', 'portrait', 'north'],
  'discover-quotes': ['discover-quotes', 'portrait', 'north'],
  'discover-progress': ['discover-progress', 'portrait', 'north'],
  'discover-rooms': ['discover-rooms', 'portrait', 'north'],
  'type-new-build': ['type-new-build', 'square', 'centre'],
  'type-extension': ['type-extension', 'square', 'centre'],
  'type-renovation': ['type-renovation', 'square', 'centre'],
  'tier-economical': ['tier-economical', 'square', 'centre'],
  'tier-standard': ['tier-standard', 'square', 'centre'],
  'tier-premium': ['tier-premium', 'square', 'centre'],
  'calc-flooring': ['calc-flooring', 'square', 'centre'],
  'calc-paint': ['calc-paint', 'square', 'centre'],
  'calc-skirting': ['calc-skirting', 'square', 'centre'],
  'calc-wallpaper': ['calc-wallpaper', 'square', 'centre'],
  'calc-openings': ['calc-openings', 'square', 'centre'],
  'calc-general': ['calc-general', 'square', 'centre'],
  'empty-projects': ['empty-projects', 'land', 'centre'],
  'empty-rooms': ['empty-rooms', 'land', 'centre'],
  'empty-quotes': ['empty-quotes', 'land', 'centre'],
  'empty-costs': ['empty-costs', 'land', 'centre'],
  'empty-procurement': ['empty-procurement', 'land', 'centre'],
  'home-header': ['home-header', 'wide', 'north'],
  'paywall-header': ['paywall-header', 'wide', 'centre'],
  'signin-hero': ['signin-hero', 'portrait', 'north'],
};
/** The one stand-in for slots whose photo is not generated yet. */
const PLACEHOLDER = 'placeholder';

const have = new Set(readdirSync(SRC).filter((f) => f.endsWith('.png')).map((f) => f.replace(/\.png$/, '')));
const made = {};
for (const [key, [src, size, gravity]] of Object.entries(SLOTS)) {
  if (!have.has(src)) continue;
  const [w, h] = SIZE[size];
  await sharp(join(SRC, `${src}.png`))
    .resize(w, h, { fit: 'cover', position: gravity === 'north' ? 'north' : 'centre', kernel: 'lanczos3' })
    .jpeg({ quality: 82, progressive: true, mozjpeg: true })
    .toFile(join(OUT, `${key}.jpg`));
  made[key] = true;
}
// The placeholder: a calm crop of the house frame (wide enough for any slot).
await sharp(join(SRC, 'type-new-build.png')).resize(1200, 900, { fit: 'cover' }).jpeg({ quality: 80, progressive: true, mozjpeg: true }).toFile(join(OUT, `${PLACEHOLDER}.jpg`));

const lines = Object.keys(SLOTS).map((key) => `  '${key}': require('../../assets/images/${made[key] ? key : PLACEHOLDER}.jpg'),${made[key] ? '' : ' // placeholder until Codex makes it'}`);
const ts = `/* eslint-disable */
// GENERATED by design/tools/process-images.mjs: do not edit by hand.
// One image map for the whole app. Slots marked "placeholder" point at the one
// stand-in image until their Codex photo exists; re-run the script to swap.
export const IMAGES = {
${lines.join('\n')}
  placeholder: require('../../assets/images/${PLACEHOLDER}.jpg'),
} as const;

export type ImageKey = keyof typeof IMAGES;
export const PLACEHOLDER_KEYS: ImageKey[] = [${Object.keys(SLOTS).filter((k) => !made[k]).map((k) => `'${k}'`).join(', ')}];
`;
mkdirSync(join(ROOT, 'mobile', 'src', 'assets'), { recursive: true });
writeFileSync(join(ROOT, 'mobile', 'src', 'assets', 'images.ts'), ts);
console.log(`processed ${Object.keys(made).length}/${Object.keys(SLOTS).length}; placeholders: ${Object.keys(SLOTS).filter((k) => !made[k]).join(', ') || 'none'}`);
if (!existsSync(join(OUT, `${PLACEHOLDER}.jpg`))) process.exit(1);
