/* eslint-disable */
// GENERATED by design/tools/process-images.mjs: do not edit by hand.
// One image map for the whole app. Slots marked "placeholder" point at the one
// stand-in image until their Codex photo exists; re-run the script to swap.
export const IMAGES = {
  'discover-budget': require('../../assets/images/discover-budget.jpg'),
  'discover-compare': require('../../assets/images/discover-compare.jpg'),
  'discover-finish': require('../../assets/images/discover-finish.jpg'),
  'discover-quotes': require('../../assets/images/discover-quotes.jpg'),
  'discover-progress': require('../../assets/images/discover-progress.jpg'),
  'discover-rooms': require('../../assets/images/discover-rooms.jpg'),
  'type-new-build': require('../../assets/images/type-new-build.jpg'),
  'type-extension': require('../../assets/images/type-extension.jpg'),
  'type-renovation': require('../../assets/images/type-renovation.jpg'),
  'tier-economical': require('../../assets/images/tier-economical.jpg'),
  'tier-standard': require('../../assets/images/tier-standard.jpg'),
  'tier-premium': require('../../assets/images/tier-premium.jpg'),
  'calc-flooring': require('../../assets/images/calc-flooring.jpg'),
  'calc-paint': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'calc-skirting': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'calc-wallpaper': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'calc-openings': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'calc-general': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'empty-projects': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'empty-rooms': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'empty-quotes': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'empty-costs': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'empty-procurement': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'home-header': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'paywall-header': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  'signin-hero': require('../../assets/images/placeholder.jpg'), // placeholder until Codex makes it
  placeholder: require('../../assets/images/placeholder.jpg'),
} as const;

export type ImageKey = keyof typeof IMAGES;
export const PLACEHOLDER_KEYS: ImageKey[] = ['calc-paint', 'calc-skirting', 'calc-wallpaper', 'calc-openings', 'calc-general', 'empty-projects', 'empty-rooms', 'empty-quotes', 'empty-costs', 'empty-procurement', 'home-header', 'paywall-header', 'signin-hero'];
